# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mael1701
  password: Lesconil29
  host: localhost

development:
  <<: *default
  database: portfolio-mael-micout

test:
  <<: *default
  database: your_project_name_test

production:
  <<: *default
  database:  portfolio-mael-micout
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_HOST'] %>
